### ISSUE TITLE
todo:

### ISSUE THREAD

**Issue by mk4111** [hutosaha/hrns-#158]
#### 16/05/2016

- [x] replace keys in redis, so that they can be easily identified
- [x] merge work
- [x] see why candidates (submitted by agency) aren't showing up on admin page - bug in mk4111's code ?
- [x] finish nodejs unoconv conversion
- [x] make a catch for 'undefined' keys
